# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1"
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "192.168.176.55:53:53/tcp"
      - "192.168.176.55:53:53/udp"
      - "8083:80/tcp"
      - "8445:443/tcp"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'Europe/Berlin'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      WEBPASSWORD: '<password>'
    hostname: pihole
    dns:
      - 192.168.176.1
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE
      - CAP_CHOWN
    labels:
      - autoheal=true
