services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
    ports:
      - 8081:80
      - 8443:443
    restart: unless-stopped
