services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    restart: always
    ports:
      - 8082:80
      - 8444:443
    volumes:
      - ./opt-deconz:/opt/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - TZ=Europe/Berlin
      - DECONZ_BAUDRATE=115200
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
      - DECONZ_DEVICE=/dev/ttyUSB0
